# Feature: upstream spot-cone ownership identity

Status: superseded locally (see below), still proposed upstream
Owner: `noise-mirror/`, `volcano-territory.lua` (implementation); `tools/noise-sandbox/` (evidence)
Config: Factorio 2.x map generation; Vulcanus/EoN volcano spot systems

## Why

Volcano cones are generated by `spot_noise`, but the noise-expression API returns
only the cone height. It does not return which selected spot produced that height.
EoN therefore cannot give each volcano cone a stable, unique territory index in a
noise expression. The workaround -- a `voronoi_cell_id` cell plus a field
threshold -- introduces artificial cell boundaries that cut volcanoes into extra
territories, and the shape of the real volcano (its cone centre and its effective
width) is only known through the field's own thresholds.

EoN now recovers the identity at runtime instead (`noise-mirror/`), which works but
had to re-implement the candidate RNG, the minimum-spacing dart throw, the
favorability trim and the cone geometry from a reverse-engineered specification.

This is an upstream engine capability request, not a player-visible EoN feature.
The requested primitive should expose the owner of the winning `spot_noise` cone
without changing the existing height result.

## Proposed engine API

Add a scalar noise expression, tentatively named `spot_noise_id`, with the same
parameters and candidate-selection semantics as `spot_noise`:

```lua
spot_noise_id{
    x = x,
    y = y,
    seed0 = map_seed,
    seed1 = 1,
    region_size = 256,
    candidate_spot_count = 1,
    suggested_minimum_candidate_point_spacing = 1500,
    skip_span = 1,
    skip_offset = 0,
    density_expression = ...,
    spot_quantity_expression = ...,
    spot_radius_expression = ...,
    spot_favorability_expression = ...,
    basement_value = 0,
    maximum_spot_basement_radius = 500,
}
```

The exact name and return encoding are for the engine API discussion. The required
semantics are more important than the spelling.

## Acceptance criteria

- [ ] AC-1 **Winning-cone agreement.** At every position, `spot_noise_id` returns
      the identity of the same selected candidate whose cone supplies the value of
      `spot_noise`, including candidate favorability, quantity, radius, skip
      stream, and deterministic tie-breaking.
- [ ] AC-2 **Stable identity.** The returned ID is deterministic for the same map
      seed and spot parameters, constant wherever one selected cone owns the
      position, and distinct for distinct selected candidates.
- [ ] AC-3 **Overlap ownership.** Where two spot systems overlap, the ID identifies
      exactly one owner using the same maximum-cone/tie rule as the corresponding
      `max(spot_noise_a, spot_noise_b)` expression. The ID must not select a
      different candidate merely because it is nearest.
- [ ] AC-4 **Multiple spot systems.** Separate `seed1`/candidate streams cannot
      accidentally return colliding IDs. The API must either include a stream
      discriminator or otherwise guarantee collision-free IDs across independently
      configured spot systems.
- [ ] AC-5 **No duplicate work.** The engine should retain candidate identity from
      the normal `spot_noise` evaluation rather than independently rerunning
      candidate generation and selection for every ID query. A combined internal
      result is acceptable if the public expression remains scalar.
- [ ] AC-6 **Boundary behavior.** Crossing from one cone owner to another may
      change the ID, but the transition must be deterministic and must agree with
      the height-field transition. The API must not introduce arbitrary
      `voronoi_cell_id`-style boundaries.
- [ ] AC-7 **Compatibility.** Existing `spot_noise` expressions retain their exact
      numeric results, performance characteristics, and compiler behavior. The new
      primitive is opt-in.
- [ ] AC-8 **EoN use case.** With the primitive available, EoN can form a
      volcano identity from the small and big spot systems and use the existing
      west/east gradient split without a `voronoi_cell_id` seam. The index must
      remain finite only on the intended volcano mask and `-inf` elsewhere.

## Status: superseded locally, still worth asking upstream

Factorio 2.0's `spot_noise` still returns only the cone height, so this request
stands. EoN no longer depends on it: `noise-mirror/` reconstructs the cone
identity at runtime from the documented selection algorithm (see
tools/noise-sandbox/vendor/FactorioMapWebUI/docs/noise/spot-noise-NOTES.md), and
`volcano-territory.lua` turns that into one `surface.create_territory` call per
cone. The reconstruction is verified against the engine's own selection
(tests/spot_mirror_parity.py: 0 unexplained owner mismatches over four
seed/frequency/size configurations).

The reconstruction depends on facts that are reverse-engineered rather than
documented, which is exactly why the API is still wanted: if `spot_noise_id`
existed, EoN would not need a mirror of the candidate RNG, the dart throw, the
favorability trim or the cone geometry, and the identity would be guaranteed
rather than measured. Two of the local reconstruction's costs are direct
consequences of the missing primitive:

* the spot-deployment warp (`eon_detail_noise_at` on the query) is not mirrored,
  which moves ~1-3% of chunk ownership decisions to a cone rim (measured, always
  within one chunk);
* the cone-existence gate has to read the rendered tile rather than the engine's
  own density expression, so a cone is only decidable once its centre chunk is
  generated.

## Verification

Upstream implementation tests should cover at least:

- one isolated spot;
- two non-overlapping spots;
- two overlapping spots with a known winner;
- a spot crossing a noise region boundary;
- separate `seed1` streams;
- ties and near-ties;
- different map seeds;
- parity with `spot_noise` over a dense grid.

For EoN, the existing probes can then verify the user-visible result:

```sh
python3 tests/probe_split_grouping.py 620294650 tests/map-gen-settings-user.json
python3 tests/probe_split_grouping.py 12345 tests/map-gen-settings-high-volcanism.json
```

The relevant comparison is not just the territory count. The probes must compare
canonical per-chunk territory shapes and verify that volcano-cone ownership does
not introduce artificial top/bottom cell splits.

## Rejected alternatives

- **`voronoi_cell_id`:** rejects because its spatial boundaries do not follow
  `spot_noise` candidates and cut cones into extra territories.
- **`voronoi_spot_noise`:** rejects because it measures distance to an independent
  Voronoi point and does not return the selected `spot_noise` candidate identity.
- **Quantized cone height:** rejects because height changes throughout a cone and
  its maximum has no stable object identity.
- **A separate candidate-selection pass for IDs:** rejects as the default engine
  implementation because it repeats expensive spot selection; the identity should
  be retained by the normal `spot_noise` evaluation.
- **Lua territory creation from current tiles alone:** that is what EoN ended up
  doing, and it is enough -- the mirror rebuilds the candidate identity from the
  documented selection algorithm, so ownership is decided per chunk without waiting
  for a connected component to be discovered. It remains a mirror, not the API.
